### ISSUE TITLE
lnetatmo stops after running some hours / days

### ISSUE THREAD

**Issue by schroepfer** [philippelt/netatmo-api-python#21]
Hello, and thank you for your work.
but I have a problem with the software, which I can't solve.

Afer some hours or some days lnetatmo stops his work with the following message:

Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124] on linux
Type "copyright", "credits" or "license()" for more information.
>>> 
========== RESTART: /home/pi/netatmo/write_NetAtmo_to_ThingSpeak.py ==========
Traceback (most recent call last):
  File "/home/pi/netatmo/write_NetAtmo_to_ThingSpeak.py", line 11, in <module>
    authorization = lnetatmo.ClientAuth()
  File "/home/pi/netatmo/lnetatmo.py", line 157, in __init__
    if not resp: raise AuthFailure("Authentication request rejected")
lnetatmo.AuthFailure: Authentication request rejected
>>> 

My authorization for NetAtmo is hard codet in lnetatmo.py.

Regards
Juergen

**Comment by philippelt** [comment]
Hello, I just checked again and don't find any problem. All my tests are Ok.

I would recommend to check : 
- the validity of authentication data used. Several users reported that they needed to refresh their client id and secret for unknown reasons.
- the lack of environment variables (USERNAME, PASSWORD, CLIENT_ID, CLIENT_SECRET) that would change authentication information at run time (Your are calling ClientAuth init without parameters)
- the throttling of your requests. Netatmo has a strong policy regarding requests frequency which is a good practice to ensure service quality for everyone. If your request data to fast, you can be banned for some hours. In such case, the authentication should work again without change after 24h.

Please, if you made it works due to configuration issue, post here the solution you may found to the problem. It may help an other user with the same error.

Yours
Philippe

**Comment by schroepfer** [comment]
Thank you for fast response!
I refreshed my id and secret now.
I read the data all 15 minutes now. (in the past all 10min.)

I let it run and we will see....

**Comment by philippelt** [comment]
To keep code simple, I do not try to catch all Netatmo possible errors, even including rate limiting.

I do not have applications that run continuously interacting with Netatmo servers. I rather use several alarm tasks, that runs as single shot every half an hour, and take actions depending on temperature.

Periodically, one of these tasks will fail because of any possible failure scenario. My wifi may be disturbed for some seconds precisely at the time the request is sent, my internet access can be down for a few seconds or minutes, my provider DNS may fail to resolve the server names, the Netatmo server may be unreachable for whatever reason (unfortunately, not unusual), etc... The service chain is so long that there are many possible failure scenarios.

In case of error, my programs just gave up as they will be restarted on the next time slot.

This issue of complex service chain is the reason why I switched to Zwave based temperature monitoring for any critical monitoring requirement. My server is directly connected to the sensor using just a Zwave controller USB key, nothing else, not even the LAN or Wifi. For 3 years now, I have been impressed by the reliability of this setup !
