### ISSUE TITLE
Broken by api change

### ISSUE THREAD

**Issue by berkinet** [philippelt/netatmo-api-python#43]
An API change seems to have broken this module.
https://forum.netatmo.com/viewtopic.php?f=5&t=19196

**Comment by philippelt** [comment]
Many thanks for the information.

After reading the linked post, it seems that there is no way to avoid an  API breaking change. Netatmo historic long tradition.

As the previous property "station name" that was used to identify a station is definitely lost and replaced by a home name, I am going to be obliged to remove all station_name features (selecting data for a given station for example) and replace it where it is possible by home name.

They have kindly provided, for compatibility they said, a station_name field but they just decided to provide **new content into it** ! This is obviously what netatmo call legacy compatiblity 👎 

For existing code using the library :  

- If you don't specify a station name in your code and have only one home, your code should continue to work as expected (the default station will be handled by the default home mechanism)
- if you had defined a second home for the use of cameras for example, it may break your code if this home, dedicated to camera use, is selected as the default home and there is no weather station associated.
- if you used to specify a station name in your requests, you will have to change your code a replace the station name by a home name

I am working on these changes. If you have any remarks or idea about how to ease transition for existing applications, feel free to provide suggestions...

**Comment by berkinet** [comment]
Philippe:

Thanks for the quick reply.  I use lnetatmo inside of a plugin for a home automation system (Indigo).  Since my use implies a separate instance for each home, and I only support the weather module, I created a quick fix by just global changing station_name to home_name in the WeatherStationData class.  That works for my needs, though it is not really the right fix.

Richard

**Comment by philippelt** [comment]
A lot of things look currently broken at netatmo for the moment. The time_utc return for measurement seems lost somewhere in translation. It displays something near 6 hours from reality (thus breaking all attempts to confirm measurement validity).

The IOS app says measurement is a few minutes old but curves are also showing the big shift of several hours...

I used the Web interface to see if things are the same. It's worst, there is the list of sensors on the left column but not any value is displayed as current (probably because they consider values to old to be appropriate). Curves in the middle shows also the big time shift.

I am going to wait some days to see if netatmo can restore normal operations.

For your information, digging in the web menus that I didn't checked for a long time, I discover that despite my station data is not selected to be public (in privacy settings), there were two apps that I didn't know that were given access to my station ! One is a "public pro" weather service ???

**Comment by berkinet** [comment]
I agree. It makes sense to wait a a few days, or weeks even.

**Comment by berkinet** [comment]
Thanks. I will download and test in my application today.

**Comment by berkinet** [comment]
All ok! 

Merci, et passez des bonnes fêtes.

**Comment by philippelt** [comment]
Merci, vous aussi !
