### ISSUE TITLE
exceptions when no homes 

### ISSUE THREAD

**Issue by mvillarejo** [philippelt/netatmo-api-python#6]
Thanks for the module, I belive I just found a bug whilst only using netatmo station and you do not use the camera, it looks like the rawData does not have homes setup
`285        self.homes = { d['id'] : d for d in self.rawData['homes'] }`

`{u'homes': [], u'user': {u'lang': u'es-ES', u'reg_locale': u'es-ES', u'country': u'ES_ES'}, u'global_info': {u'show_tags': True}}`

and therefore there's an out of range exception:

Traceback (most recent call last):
  File "lnetatmo.py", line 562, in <module>
    Camera = WelcomeData(authorization)
  File "lnetatmo.py", line 307, in __init__
    self.default_home = list(self.homes.values())[0]['name']
IndexError: list index out of range

**Comment by philippelt** [comment]
hello,

first, thanks for taking time to report.

If I understand, your are authenticating with read_camera scope and asks for camera data will you don't have a camera on your account : an exception is thrown which doesn't look unexpected to me as there is no camera.

May be I missed your point, what would be the expected behavior for you ?

I didn't put almost any code for exception management. If anything do not work as expected, you will have to manually check what is wrong. As this library is used for automated/unattended tasks, exception will always require a human diagnostic and thus must be monitored.

Not catching exception mean that I will have the direct original information (traceback) for debugging

**Comment by mvillarejo** [comment]
Hey, thanks for your quick response. 

The place where I'm using it is within home-assistant, and the way it is implemented there, it starts the module using all the scopes and that's why it throws an error, check this issue for details:
https://github.com/home-assistant/home-assistant/issues/2678

Regards,

**Comment by philippelt** [comment]
Thanks for clarifying,

I understand that there is a systematic enumeration of any device class (weather station, camera) without knowing if any exists. In the discovery code (components/camera/netatmo.py) there is no exception trap on line 30 which happen in case no camera is available.

It's likely that the same problem would appear in the sensor module (components/sensor/netatmo.py) if connected to an account without a weather station connected.

In both cases, the exception should be handled to conclude that this device class (weather station or camera) has no instance and discovery should skip to an other device.

Of course, this would hide a transient anomaly but this is the drawback of discovery based configuration : this is why I consider discovery not appropriate for any critical monitoring/alarm system.

By the way, the discovery model could work with exception trapped, this has to be fixed in the home_assistant source code...

I will evaluate returning None on enumeration of camera or weatherstation when no device is available but I need to analyze potential side effects : for my own needs, None would be an anomaly and I would need to test for None and raise an Exception to trigger an alarm... which is currently done by current behavior !

Yours

**Comment by philippelt** [comment]
Finally, I added a lnetatmo.NoDevice exception that will be raised if no device is present when accessing WeatherStationData or WelcomeData to help proper implementation when discovery is used and eliminate the temptation of unscoped exception trap.

This will maintain forward compatibility as an exception is still raised and will abort existing code execution.

Appropriate use is now (for weather station) : 

```python
try:
    devList = lnetatmo.WeatherStationData(auth)
except lnetatmo.NoDevice :
    Do something if no station is present (including exiting, reraising, ...)

#devList can now be used because there is at least one station
```

**Comment by mvillarejo** [comment]
Thanks a lot for that, let's see if the guys from home-assistant tune a bit their implementation.

Regards,
